services:
  api:
    build: .
    container_name: spring-api
    ports:
      - "8080:8080"
    env_file:
      - .env

#  db:
#    image: postgres:16
#    container_name: postgres-db
#    ports:
#      - "5433:5432"
#    environment:
#      POSTGRES_DB: macrocalculator
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#volumes:
#  pgdata:
