services:
#  api:
#    build: .
#    container_name: spring-api
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/macrocalculator
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#    depends_on:
#      - db

  db:
    image: postgres:16
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: macrocalculator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
